version: "3"
services: 
    mongodb:
      image: mongo:latest
      hostname: mongodb
      environment:
        - MONGO_INITDB_DATABASE=mockdb
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        - MONGO_INITDB_ROOT_PASSWORD=secret
     
      ports:
        - 27017:27017
    
    mockapiserver:
        image: mockapiserver:latest
        depends_on: 
            - mongodb
        ports:
            - 8082:8082